### PR TITLE
test-code highligt

### PR DESCRIPTION
**Pull request by DaeunYoon**
Check out: http://localhost:3000/tests/code
image

I introduced babel here for bundling `solidity` language here and [this is how they officially support it](https://prismjs.com/index.html#basic-usage-bundlers).
As `prismjs` library doesn't solidity & other plugins
: [similar problem issue](https://github.com/PrismJS/prism/issues/1789)

Currently `Highlight` component has settings like below: 
plugins ('line-numbers'),  them('prism-okaidia'),  language('solidity')

### CODE REVIEW

**Comment by DaeunYoon** [comment]
@valiafetisov 
This doesn't have any other function but rendering the solidity code with syntax highlight :) 
As you said you'll look for the code highlight library, maybe you can have a look at it!

**Comment by valiafetisov** [comment]
Thanks! My observations:
- Two biggest contenders, [according to npm trends](https://npmtrends.com/highlight.js-vs-prism-vs-prismjs-vs-rainbow-code-vs-syntax-highlighter), seems to be `highlight.js` and `prism.js`

- `highlight.js` https://highlightjs.readthedocs.io/en/latest/index.html
  - Provides [static "rule definition" to specify detectors](https://highlightjs.readthedocs.io/en/latest/language-guide.html#general-syntax) and detect specific parts of the code using plain regexp + keywords or other high-level methods
    - Regexp would be enough in our case to specify start and end of the line, but not the line number (so that's a problem on the first glance)
  - Then the detection is turned into the html markup (detected element is wrapped into a `span` with class names [generated from the rule `scope` argument](https://highlightjs.readthedocs.io/en/latest/language-guide.html#markup-generation))
  - You can add your own custom rules on top of existing ones
  - There are some kind of [js hooks](https://highlightjs.readthedocs.io/en/latest/plugin-recipes.html) that you can define to run custom js on detection, but they are not documented except one fired after the whole code is processed
  - Conclusion: there is not enough functionality to add links, as it's only focused on highlighting and easy rule definition. It might be possible, but super hacky
- `prism.js`
  - have awful main page https://prismjs.com
  - goes beyond code highlighting
  - modular and plugin-based, eg
    - have plugin for line highlighting https://prismjs.com/plugins/line-highlight/
    - have plugin for line numbers https://prismjs.com/plugins/line-numbers/
    - have plugin for links (very close to what we need!) https://prismjs.com/plugins/autolinker/
    - have plugin for colors displayed in tooltips (the stretch requirement) https://prismjs.com/plugins/previewers/
  - even if it's not possible to use it to do what we need using their API, it will be possible to use their [Keep Markup](https://prismjs.com/plugins/keep-markup/) feature to add links ourselves and then apply rest of the things via this library!
  - Conclusion: this package seems to fulfil the requirements for us

Overall conclusion: let's add prism.js instead of the highlight.js here (and maybe move index page to `/tests/code` so we don't have code conflicts in the future)

**Comment by DaeunYoon** [comment]
> let's add prism.js instead of the highlight.js here (and maybe move index page to /tests/code so we don't have code conflicts in the future)

Sounds good! 
I'll then for now implement basic code highlight in test page. 
And once we know which plugin to use to render we can implement so.

**Comment by valiafetisov** [comment]
> I'll then for now implement basic code highlight in test page.

Great, after that we can even merge it! Once merged I can also look into defining custom plugins

**Comment by valiafetisov** [comment]
Looking good!
Screenshot 2023-08-06 at 11 27 18

**Pull request merged**
