### PR TITLE
Add support for variable address detection

### PR DESCRIPTION
**Pull request by KirillDogadin-std**
Adding support for the address detection in the cases when:
  - variable is declared in some block (e.g. functions)
  - variable is declared as state (e.g. on the level of the contract)

### CODE REVIEW

**Comment by KirillDogadin-std** [comment]
tested state variables on http://localhost:3000/api/linking/goerli/0x4Ca8451B5a598aba0160F35505402fad9713fb0c

**Comment by KirillDogadin-std** [comment]
tested manually for the ordinary variables. (did not find the contract)

1.  `npx prisma studio`
2. replace the src code in some contract (that has a single file)
3. run the endpoint
4. compare `range` (not `loc`) because copypasting apparently removes the newline chars.

Contract i've tested with:

```

contract SparkPayloadGoerli
{
  function getPoolContext() public pure override returns (IEngine.PoolContext memory) {
    address kek = 0x1234567890123456789012345678901234567890;
    asdf(kek);
    address kek2 = someFunc();
    address kek3 = ASDF(0x1234567890123456789012345678901234567890).someFunc();
    address kek4 = ASDF(KEKA).someFunc();
    return IEngine.PoolContext({networkName: 'Goerli', networkAbbreviation: 'Gor'});
  }
}
```

**Comment by DaeunYoon** [comment]
```sol
contract MainTest {
    address public constant ADDRESS = 0x1234567890123456789012345678901234567890;
    function test() public returns (address) {   
      address addr = 0x1234567890123456789012345678901234567890; 
      someOtherFn(addr);
      anotherFn('0x1234567890123456789012345678901234567890');
      return ADDRESS;  
     }
}
```
It seems to working for me :D

**Comment by KirillDogadin-std** [comment]
> It seems to working for me :D 

please pay attention to the `loc` and `range` vaulues (because we would not like them to be incorrect / of undesired values.)

If you did not compare them before (in the `'hardcoded'` PR) , also this should be compared :)

**Comment by DaeunYoon** [comment]
```
contract MainTest {
    address public constant ADDRESS = 0x1234567890123456789012345678901234567890;
    function test() public returns (address) {   
      address addr = 0x1234567890123456789012345678901234567890; 
      someOtherFn(addr);
      anotherFn('0x1234567890123456789012345678901234567890');
      return ADDRESS;  
     }
}
```

- first `0x1234567890123456789012345678901234567890` hardcoded shows up twice
- `anotherFn('0x1234567890123456789012345678901234567890');` doesn't show up
The others are correct

**Comment by KirillDogadin-std** [comment]
I suggest the type system so that you could infer the actions that need to be done on frontend. Something along the lines:

```
interface Hardcoded {
  type: 'hardcoded'
  value: '0x123...'
}
interface EthersCall {
  type: 'ethers'
  contractAddress: '0x...`
  functionName: 'functionName'
  args: any[]
}.
```
I adjust code to return these under `getAddress` and we can use the frontend logic to build actual functions from this.


Opinions on the above? @valiafetisov @DaeunYoon

**Comment by KirillDogadin-std** [comment]
> first 0x1234567890123456789012345678901234567890 hardcoded shows up twice

idk looks like library problem. Try again, i've hacked the fix for it.

> doesn't show up The others are correct

that's because the address you've provided is not an address since it's in quotes `'`

**Comment by DaeunYoon** [comment]
tested with a few other code snaps and lgtm!

**Pull request merged**
